require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wish_items", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WishItem. As you add validations to WishItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WishItem.create! valid_attributes
      get wish_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wish_item = WishItem.create! valid_attributes
      get wish_item_url(wish_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wish_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      wish_item = WishItem.create! valid_attributes
      get edit_wish_item_url(wish_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WishItem" do
        expect {
          post wish_items_url, params: { wish_item: valid_attributes }
        }.to change(WishItem, :count).by(1)
      end

      it "redirects to the created wish_item" do
        post wish_items_url, params: { wish_item: valid_attributes }
        expect(response).to redirect_to(wish_item_url(WishItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WishItem" do
        expect {
          post wish_items_url, params: { wish_item: invalid_attributes }
        }.to change(WishItem, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post wish_items_url, params: { wish_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wish_item" do
        wish_item = WishItem.create! valid_attributes
        patch wish_item_url(wish_item), params: { wish_item: new_attributes }
        wish_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wish_item" do
        wish_item = WishItem.create! valid_attributes
        patch wish_item_url(wish_item), params: { wish_item: new_attributes }
        wish_item.reload
        expect(response).to redirect_to(wish_item_url(wish_item))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        wish_item = WishItem.create! valid_attributes
        patch wish_item_url(wish_item), params: { wish_item: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wish_item" do
      wish_item = WishItem.create! valid_attributes
      expect {
        delete wish_item_url(wish_item)
      }.to change(WishItem, :count).by(-1)
    end

    it "redirects to the wish_items list" do
      wish_item = WishItem.create! valid_attributes
      delete wish_item_url(wish_item)
      expect(response).to redirect_to(wish_items_url)
    end
  end
end
